---
- name: Inspect deployment secrets
  command:
    argv: [docker, secret, inspect, "{{ deployment_secret_names[item.key] }}"]
  loop: "{{ deployment_secret_material | dict2items }}"
  register: deployment_secret_inspect
  changed_when: false
  failed_when: false
  no_log: true

- name: Create missing deployment secrets
  command:
    argv: [docker, secret, create, "{{ deployment_secret_names[item.item.key] }}", '-']
    stdin: "{{ item.item.value }}"
    stdin_add_newline: false
  loop: "{{ deployment_secret_inspect.results }}"
  when: item.rc != 0
  no_log: true
