services:

  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: postgres_database
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./backend/
    image: "${API_IMAGE:-off-key-api:latest}"
    container_name: fastapi_backend
    env_file: .env
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
      - socket-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      retries: 5

  socket-proxy:
    container_name: socket-proxy
    image: tecnativa/docker-socket-proxy
    restart: always
    networks:
      - socket-network
    privileged: true # true for VM. False for unprivileged LXC container/podman
    ports:
    #  - "127.0.0.1:2375:2375" # Port 2375 should only ever get exposed to the internal network. When possible use this line.
    # To manage multiple docker endpoints within a network, use the following line:
     - "2375:2375"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - LOG_LEVEL=info # debug,info,notice,warning,err,crit,alert,emerg
      ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      # 0 to revoke access.
      # 1 to grant access.
      ## Granted by Default
      - EVENTS=1
      - PING=1
      - VERSION=1
      ## Revoked by Default
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=1 # Container(s) Lifecycle Management
      # Not always needed
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1 # Traefik, portainer, etc.
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1 # Portainer
      - INFO=1 # Portainer
      - NETWORKS=1 # Portainer
      - NODES=0
      - PLUGINS=0
      - SERVICES=1 # Portainer
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1 # Portainer
      - VOLUMES=1 # Portainer

  frontend:
    build: ./frontend
    image: "${FRONTEND_IMAGE:-off-key-frontend:latest}"
    container_name: react_frontend
    env_file: .env
    ports:
      - "${FRONTEND_PORT}:5173"
    depends_on:
      - api
    networks:
      - app-network
    volumes:
      - ./frontend:/src
      - /src/node_modules  # Prevent conflicts

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP port

    networks:
    - app-network

networks:
  app-network:
    driver: bridge
  socket-network:
    driver: bridge

volumes:
  postgres_data:
