services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    container_name: postgres_database
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend/
      args:
        SERVICE_NAME: off-key-api-gateway
        SERVICE_ROOT: services/api
    image: "${API_IMAGE:-off-key-api-gateway:latest}"
    container_name: api_gateway
    env_file: .env
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      postgres:
        condition: service_healthy
      socket-proxy:
        condition: service_started
    networks:
      - app-network
      - socket-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      retries: 5
    command: ["uvicorn", "off_key_api_gateway.main:app",
              "--reload", "--reload-dir", "/app/lib/python3.12/site-packages/off_key_api_gateway",
              "--host", "0.0.0.0", "--port", "8000"]
    develop:
      watch:
        - action: sync
          path: backend/services/api/src/off_key_api_gateway
          target: /app/lib/python3.12/site-packages/off_key_api_gateway
        - action: rebuild
          path: ./backend/uv.lock

  socket-proxy:
    container_name: socket-proxy
    image: tecnativa/docker-socket-proxy
    restart: always
    networks:
      - socket-network
    privileged: true # true for VM. False for unprivileged LXC container/podman
    ports:
    #  - "127.0.0.1:2375:2375" # Port 2375 should only ever get exposed to the internal network. When possible use this line.
    # To manage multiple docker endpoints within a network, use the following line:
     - "2375:2375"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - LOG_LEVEL=info # debug,info,notice,warning,err,crit,alert,emerg
      ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      # 0 to revoke access.
      # 1 to grant access.
      ## Granted by Default
      - EVENTS=1
      - PING=1
      - VERSION=1
      ## Revoked by Default
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=1 # Container(s) Lifecycle Management
      # Not always needed
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1 # Traefik, portainer, etc.
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1 # Portainer
      - INFO=1 # Portainer
      - NETWORKS=1 # Portainer
      - NODES=0
      - PLUGINS=0
      - SERVICES=1 # Portainer
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1 # Portainer
      - VOLUMES=1 # Portainer

  frontend:
    build: ./frontend
    image: "${FRONTEND_IMAGE:-off-key-frontend:latest}"
    container_name: react_client
    env_file: .env
    ports:
      - "${FRONTEND_PORT}:5173"
    depends_on:
      - api
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./frontend/yarn.lock

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP port

    networks:
      - app-network

  mqtt-proxy:
    build:
      context: ./backend/
      args:
        SERVICE_NAME: off-key-mqtt-proxy
        SERVICE_ROOT: services/mqtt
    image: "${MQTT_PROXY_IMAGE:-off-key-mqtt-proxy:latest}"
    container_name: mqtt_proxy
    env_file: .env
    command: ["/app/bin/python", "-m", "off_key_mqtt_proxy"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: always
    environment:
      - SERVICE_TYPE=mqtt_proxy
      - MQTT_TELEMETRY_ENABLED=true
    volumes:
      - ./logs:/app/logs  # For log persistence

  memcached:
    image: memcached:latest
    # command: memcached -vv
    ports:
      - "11211:11211"
    # hostname: "memcached-alpha"
    networks:
      - app-network

  mcrouter:
    image: ghcr.io/mszabo-wikia/mcrouter-debian-bookworm:20250621-a099b76
    environment:
      - MC_LOCAL=memcached
      - MC_SERVICE=memcached
    ports:
      - "11210:11211"
    volumes:
      - "./backend/services/mcrouter/config.json:/usr/local/mcrouter/config/config.json.template"
    command:
      - /bin/bash
      - -c
      - |
        sed "s|\$${MC_LOCAL}|$${MC_LOCAL}|g" /usr/local/mcrouter/config/config.json.template | \
        sed "s|\$${MC_SERVICE}|$${MC_SERVICE}|g" > /usr/local/mcrouter/config/config.json && \
        /usr/bin/mcrouter --config-file=/usr/local/mcrouter/config/config.json \
        -p 11211 \
        --num-proxies=1 \
        --stats-logging-interval=0 \
        --asynclog-disable \
        --probe-timeout-initial=1000 \
        --probe-timeout-max=15000 \
        --reset-inactive-connection-interval=900000 \
        --keepalive-count=6 \
        --keepalive-interval=4 \
        --keepalive-idle=30 \
        --timeouts-until-tko=6
    depends_on:
      - memcached
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  socket-network:
    driver: bridge

volumes:
  postgres_data:
  vite_cache:
    driver: local
  frontend_node_modules:
  # mcrouter_data:
    # external: true
