services:

  postgres:
    image: timescale/timescaledb:latest-pg15
    env_file: .env
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.backend == true ]
      restart_policy:
        condition: any

  api:
    image: "${API_IMAGE:-off-key-api-gateway:latest}"
    env_file: .env
    networks:
      - app-network
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
#      interval: 10s
#      retries: 5
#    environment:
#      - SYNC_ENABLED=false
    command: ["uvicorn", "off_key_api_gateway.main:app",
              "--reload", "--reload-dir", "/app/lib/python3.12/site-packages/off_key_api_gateway",
              "--host", "", "--port", "8000"]
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.backend == true ]
      restart_policy:
        condition: any

  tactic:
    image: "${TACTIC_IMAGE:-off-key-tactic-middleware:latest}"
    env_file: .env
    networks:
      - app-network
      - socket-network
    environment:
      - TACTIC_DOCKER_DEFAULT_NETWORK=off-key_emqx-network
    command: [ "/app/bin/python", "-m", "off_key_tactic_middleware" ]
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.frontend == true ]
      restart_policy:
        condition: any

  socket-proxy:
    image: tecnativa/docker-socket-proxy
    networks:
      - socket-network
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - LOG_LEVEL=info # debug,info,notice,warning,err,crit,alert,emerg
      ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      # 0 to revoke access.
      # 1 to grant access.
      ## Granted by Default
      - EVENTS=1
      - PING=1
      - VERSION=1
      ## Revoked by Default
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=1 # Container(s) Lifecycle Management
      # Not always needed
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1 # Traefik, portainer, etc.
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1 # Portainer
      - INFO=1 # Portainer
      - NETWORKS=1 # Portainer
      - NODES=0
      - PLUGINS=0
      - SERVICES=1 # Portainer
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1 # Portainer
      - VOLUMES=1 # Portainer
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any

  frontend:
    image: "${FRONTEND_IMAGE:-off-key-frontend:latest}"
    env_file: .env
    networks:
      - public-network
      - app-network
    environment:
      - __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS=demo.offk.qzz.io
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.frontend == true ]
      restart_policy:
        condition: any

  mailpit:
    image: axllent/mailpit:latest
#    volumes:
#      - mailpit_data:/data
    networks:
      - public-network
      - app-network
    environment:
      # Don't use quotes here!
      - MP_UI_AUTH=ddss:sZZvxai44lRcxtXpU0FB
    # For future reference
#    configs:
#      - source: mailpit_config
#        target: /run/docker/mailpit_user_file
#    environment:
#      - MP_UI_AUTH_FILE=/run/docker/mailpit_user_file
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.backend == true ]
      restart_policy:
        condition: any

  mqtt-proxy:
    image: "${MQTT_PROXY_IMAGE:-off-key-mqtt-proxy:latest}"
    env_file: .env
    command: ["/app/bin/python", "-m", "off_key_mqtt_proxy"]
    networks:
      - app-network
      - emqx-network
    environment:
      - SERVICE_TYPE=mqtt_proxy
      - MQTT_TELEMETRY_ENABLED=true
#    volumes:
#      - mqtt_logs:/app/logs
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.backend == true ]
      restart_policy:
        condition: any

  mqtt-radar:
    image: "${MQTT_RADAR_IMAGE:-off-key-mqtt-radar:latest}"
    env_file: .env
    command: [ "/app/bin/python", "-m", "off_key_mqtt_radar" ]
    networks:
      - app-network
      - emqx-network
    deploy:
      replicas: 1
      placement:
        constraints: [ node.labels.backend == true ]
      restart_policy:
        condition: any

#  memcached:
#    image: memcached:latest
#    ports:
#      - target: 11211
#        published: 11211
#        mode: ingress
#    networks:
#      - app-network
#    deploy:
#      replicas: 1
#      placement:
#        constraints: [ node.labels.backend == true ]
#      restart_policy:
#        condition: any

#  mcrouter:
#    image: ghcr.io/mszabo-wikia/mcrouter-debian-bookworm:20250621-a099b76
#    environment:
#      - MC_LOCAL=memcached
#      - MC_SERVICE=memcached
#    ports:
#      - target: 11211
#        published: 11210
#        mode: ingress
#    configs:
#      - source: mcrouter_config
#        target: /usr/local/mcrouter/config/config.json.template
#    command:
#      - /bin/bash
#      - -c
#      - |
#        sed "s|\$${MC_LOCAL}|$${MC_LOCAL}|g" /usr/local/mcrouter/config/config.json.template | \
#        sed "s|\$${MC_SERVICE}|$${MC_SERVICE}|g" > /usr/local/mcrouter/config/config.json && \
#        /usr/bin/mcrouter --config-file=/usr/local/mcrouter/config/config.json \
#        -p 11211 \
#       --num-proxies=1 \
#        --stats-logging-interval=0 \
#        --asynclog-disable \
#        --probe-timeout-initial=1000 \
#        --probe-timeout-max=15000 \
#        --reset-inactive-connection-interval=900000 \
#        --keepalive-count=6 \
#        --keepalive-interval=4 \
#        --keepalive-idle=30 \
#        --timeouts-until-tko=6
#    networks:
#      - app-network
#    deploy:
#      replicas: 1
#      placement:
#        constraints: [ node.labels.backend == true ]
#      restart_policy:
#        condition: any

  emqx-main:
    image: emqx/emqx:5.8.7
    environment:
      - "EMQX_NODE_NAME=emqx@emqx-main"
      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@emqx-main]"
        # See https://github.com/emqx/emqx/issues/8627#issuecomment-2833234761
        # Only works on fresh boot (no data volume!)
      - "EMQX_DASHBOARD__DEFAULT_USERNAME=ddss"
      - "EMQX_DASHBOARD__DEFAULT_PASSWORD=xMdrOJtNxRA8ZwUtjAHq"
#    healthcheck:
#      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
#      interval: 5s
#      timeout: 25s
#      retries: 5
    networks:
      emqx-network:
        aliases:
          - emqx-main
    deploy:
      replicas: 1
      placement:
        constraints: [ node.labels.backend == true ]
      restart_policy:
        condition: any

#  emqx-worker:
#    image: emqx/emqx:5.8.7
#    environment:
#      - "EMQX_NODE_NAME=emqx@{{.Node.Hostname}}.emqx-worker"
#      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
#      - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@tasks.emqx-main,emqx@tasks.emqx-worker]"
#    healthcheck:
#      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
#      interval: 5s
#      timeout: 25s
#      retries: 5
#    networks:
#      - emqx-network
#    deploy:
#      replicas: 2
#      restart_policy:
#        condition: any

# WARNING: Encrypted overlay is incompatible with Tailscale
# MTU=1280 for tailscale0 compatibility
networks:
  public-network:
    driver: overlay
    attachable: true
    driver_opts:
      com.docker.network.driver.mtu: 1280
      # encrypted: "true"
  app-network:
    driver: overlay
    driver_opts:
      com.docker.network.driver.mtu: 1280
      # encrypted: "true"
  socket-network:
    driver: overlay
    driver_opts:
      com.docker.network.driver.mtu: 1280
      # encrypted: "true"
  emqx-network:
    driver: overlay
    attachable: true
    driver_opts:
      com.docker.network.driver.mtu: 1280
      # encrypted: "true"

# Ephemeral demo
# volumes:
#  postgres_data:
#  vite_cache:
#    driver: local
#  frontend_node_modules:

# For future reference
#  configs:
#    mailpit_config:
#      file: ./dev/mailpit-user-file
