version: 1
disable_existing_loggers: false

# Override root logger to prevent double logging
root:
  level: ${LOG_LEVEL:INFO}
  handlers: []

# Service-specific logger configurations
loggers:
  mqtt-proxy:
    level: ${SERVICE_LOG_LEVEL:${LOG_LEVEL:INFO}}
    handlers: [console, file]
    propagate: false

  sqlalchemy.engine.Engine:
    level: ${SQLALCHEMY_LOG_LEVEL:INFO}
    handlers: [console_truncated, file]
    propagate: false

  sqlalchemy.dialects:
    level: ${SQLALCHEMY_LOG_LEVEL:WARNING}
    handlers: [console_truncated, file]
    propagate: false

  sqlalchemy.pool:
    level: ${SQLALCHEMY_LOG_LEVEL:WARNING}
    handlers: [console_truncated, file]
    propagate: false

  sqlalchemy.orm:
    level: ${SQLALCHEMY_LOG_LEVEL:WARNING}
    handlers: [console_truncated, file]
    propagate: false


handlers:
  file:
    class: logging.FileHandler
    level: ${LOG_LEVEL:INFO}
    formatter: detailed
    filename: ${SERVICE_LOG_FILE:/tmp/mqtt-proxy.log}
    filters: [correlation]
