name: 'Cherry pick demo-frontend into main'
on:
  pull_request:
    branches:
      - demo-frontend # Branches where the original PRs will be merged
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: write      # for actions/checkout

jobs:
  test-cherry-pick:
    runs-on: ubuntu-latest
    name: Test the cherry-pick action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: refs/pull/75/head

      - name: Cherry pick
        id: cherry-pick
        uses: wireapp/action-auto-cherry-pick@v1.0.2
        with:
          # Branch which will receive the automatic cherry-picks
          target-branch: 'main'
          pr-title-suffix: '[🍒 FRONTEND]'
          pr-creator-token: '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'

      - name: Get the output
        run:
          echo "The created PR number is ${{
          steps.cherry-pick.outputs.pr-number }}"
