name: "Cherry pick demo-frontend into main"

on:
  pull_request_target:
    branches:
      - demo-frontend
    types:
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  cherry-pick:
    name: Cherry pick merged PR into main
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Cherry pick
        id: cherry-pick
        uses: wireapp/action-auto-cherry-pick@a4a732fe8b79e3fae70362e6271b8982be5b1bc1 # v1.0.2
        with:
          target-branch: "main"
          pr-title-suffix: "[🍒 FRONTEND]"

      - name: Show created PR number
        run: echo "The created PR number is ${{ steps.cherry-pick.outputs.pr-number }}"
