name: Enforce team labels on PRs

on:
  pull_request_target:
    branches:
      - main
    types: [opened, labeled, unlabeled, synchronize, reopened]

jobs:
  require-team-label:
    name: Check team label
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Require team ownership label
        uses: mheap/github-action-required-labels@0ac283b4e65c1fb28ce6079dea5546ceca98ccbe # v5.5.2
        with:
          labels: |
            team:frontend
            team:backend
          mode: minimum
          count: 1
          add_comment: true
          message: >-
            This pull request cannot be merged into `main` because it
            doesn't include a `team:frontend` or `team:backend` label.
            Please add one before merging.
